name: Frontend CI
run-name: ${{ github.actor }} is testing the frontend 🚀

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      node_modules_cache_key: ${{ steps.cache-deps.outputs.cache-key }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Generate cache key
        id: cache-deps
        run: echo "cache-key=$(md5sum package-lock.json | cut -d ' ' -f1)" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: npm ci

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Build Next.js project
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Run unit tests
        run: npm run test

      - name: Lint code
        run: npm run lint
